// Auto-generated imagery manifest
// Generated on: 2025-09-23T05:34:46.848Z
// Do not edit this file manually - run 'npm run imagery:manifest' to regenerate

export interface ImageManifest {
  [key: string]: {
    src1200?: string;
    src2400?: string;
    blur?: string;
    fallback?: string;
  };
}

export const IMAGERY: ImageManifest = {
  "earth_globe_realistic": {
    "fallback": "/imagery/earth/earth_globe_realistic.png"
  },
  "globe_3d_with_ravens": {
    "fallback": "/imagery/earth/globe_3d_with_ravens.png"
  },
  "galaxy_spiral": {
    "fallback": "/imagery/galaxies/galaxy_spiral.jpg"
  },
  "human_AI_space": {
    "fallback": "/imagery/galaxies/human_AI_space.jpg"
  },
  "AI_DNA": {
    "fallback": "/imagery/processed/AI_DNA.png",
    "src1200": "/optimized/AI_DNA-1200.webp",
    "src2400": "/optimized/AI_DNA-2400.webp",
    "blur": "/optimized/AI_DNA-blur.webp"
  },
  "ai_construction_bridge_banner": {
    "fallback": "/imagery/processed/ai_construction_bridge_banner.png",
    "src1200": "/optimized/ai_construction_bridge_banner-1200.webp",
    "src2400": "/optimized/ai_construction_bridge_banner-2400.webp",
    "blur": "/optimized/ai_construction_bridge_banner-blur.webp"
  },
  "ai_technology": {
    "fallback": "/imagery/processed/ai_technology.jpeg",
    "src1200": "/optimized/ai_technology-1200.webp",
    "src2400": "/optimized/ai_technology-2400.webp",
    "blur": "/optimized/ai_technology-blur.webp"
  },
  "compliance_shield_premium": {
    "fallback": "/imagery/processed/compliance_shield_premium.png",
    "src1200": "/optimized/compliance_shield_premium-1200.webp",
    "src2400": "/optimized/compliance_shield_premium-2400.webp",
    "blur": "/optimized/compliance_shield_premium-blur.webp"
  },
  "data_sovereignty_badge": {
    "fallback": "/imagery/processed/data_sovereignty_badge.png",
    "src1200": "/optimized/data_sovereignty_badge-1200.webp",
    "src2400": "/optimized/data_sovereignty_badge-2400.webp",
    "blur": "/optimized/data_sovereignty_badge-blur.webp"
  },
  "elevation": {
    "fallback": "/imagery/processed/elevation.jpg",
    "src1200": "/optimized/elevation-1200.webp",
    "src2400": "/optimized/elevation-2400.webp",
    "blur": "/optimized/elevation-blur.webp"
  },
  "ireland_landscape": {
    "fallback": "/imagery/processed/ireland_landscape.jpg",
    "src1200": "/optimized/ireland_landscape-1200.webp",
    "src2400": "/optimized/ireland_landscape-2400.webp",
    "blur": "/optimized/ireland_landscape-blur.webp"
  },
  "michael_howardbio": {
    "fallback": "/imagery/processed/michael_howardbio.jpeg",
    "src1200": "/optimized/michael_howardbio-1200.webp",
    "src2400": "/optimized/michael_howardbio-2400.webp",
    "blur": "/optimized/michael_howardbio-blur.webp"
  },
  "raven_huginn": {
    "fallback": "/imagery/processed/raven_huginn.png",
    "src1200": "/optimized/raven_huginn-1200.webp",
    "src2400": "/optimized/raven_huginn-2400.webp",
    "blur": "/optimized/raven_huginn-blur.webp"
  },
  "raven_muninn": {
    "fallback": "/imagery/processed/raven_muninn.png",
    "src1200": "/optimized/raven_muninn-1200.webp",
    "src2400": "/optimized/raven_muninn-2400.webp",
    "blur": "/optimized/raven_muninn-blur.webp"
  },
  "reach_for_the_stars": {
    "fallback": "/imagery/starfields/reach_for_the_stars.png",
    "src1200": "/optimized/reach_for_the_stars-1200.webp",
    "src2400": "/optimized/reach_for_the_stars-2400.webp",
    "blur": "/optimized/reach_for_the_stars-blur.webp"
  },
  "starfield_cosmic": {
    "fallback": "/imagery/starfields/starfield_cosmic.jpg",
    "src1200": "/optimized/starfield_cosmic-1200.webp",
    "src2400": "/optimized/starfield_cosmic-2400.webp",
    "blur": "/optimized/starfield_cosmic-blur.webp"
  }
};

// Helper function to get image info
export function getImageInfo(name: string): ImageManifest[string] | null {
  return IMAGERY[name] || null;
}

// Helper function to check if image exists
export function hasImage(name: string): boolean {
  return name in IMAGERY;
}

// Helper function to get all available image names
export function getAllImageNames(): string[] {
  return Object.keys(IMAGERY);
}
