/**
 * Imagery Manifest - Generated by Sharp Pipeline
 * Source: Master Content Lock Section 9
 * Generated: 2025-09-28T15:38:42.302Z
 * 
 * This file is auto-generated. Do not edit manually.
 * Run: npm run imagery:process
 */

export const IMAGES = {
  "ai_const_doc": {
    "src": "/imagery/processed/AI_Const_doc-1200.webp",
    "src2x": "/imagery/processed/AI_Const_doc-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAwCdASoUAA0ALvmczmclLy8vDwD4SzAF2AIZzglvPBCQAP7lY1G8Iw7Ynx37hfhFCwGRNTb27uNTd3xoU5Iy51QD77VkwKt9KpHAAAA=",
    "width": 1536,
    "height": 1024,
    "aspectRatio": 1.5
  },
  "fusion_ai_ethics": {
    "src": "/imagery/processed/AI_DNA-1200.webp",
    "src2x": "/imagery/processed/AI_DNA-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAwBACdASoUABQAPzmUwFmvKiajqAgB4CcJZ12AABto8Od3rz5V6UVwbgAA/uyN7q0U+ApJmUTuUXb6J0G0R+mv0RfeWflK2Ynv154TaebukAAA",
    "width": 2048,
    "height": 2048,
    "aspectRatio": 1
  },
  "elevation": {
    "src": "/imagery/processed/ELevation-1200.webp",
    "src2x": "/imagery/processed/ELevation-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwBACdASoUABIAPzmSvFgvKiWjqAqp4CcJYwC7AAtac1kmdcfiRZSeFAAA/tC5VwKyt2CUuUqdipd39qgN0+JULXeKYRHVExmOzKb5YUg65qRzladM+EYKEsyxnPWmhhiAKAAA",
    "width": 1536,
    "height": 1349,
    "aspectRatio": 1.1386212008895478
  },
  "feather": {
    "src": "/imagery/processed/Feather-1200.webp",
    "src2x": "/imagery/processed/Feather-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAABwBACdASoUABQAPyV8slOuKCSit/qoAcAkiWcAAFu0JU+pkOWGfMks6UaZQAD+6/LDs6wUVF/UtDzOBxYwLTGYMKAAAA==",
    "width": 2048,
    "height": 2048,
    "aspectRatio": 1
  },
  "footer_logo_hisl": {
    "src": "/imagery/processed/HISL_Logo-1200.webp",
    "src2x": "/imagery/processed/HISL_Logo-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAACwAwCdASoUABUAPzmIu1avKKWjsBgIAeAnCWUAACIYFYo04Sbt0AD+6/8kyITccZdzv1Oybc4c8u4craRXvRW17TAAAA==",
    "width": 1065,
    "height": 1104,
    "aspectRatio": 0.9646739130434783
  },
  "home_problem_main": {
    "src": "/imagery/processed/Hard_Hat_ digital_paperwork-1200.webp",
    "src2x": "/imagery/processed/Hard_Hat_ digital_paperwork-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBQCdASoUABQAPzWEvFOvKKaisBgMAeAmiUAXyQIHQZXjjoaLZitAjokNdWw5QwJUAAD+y9addMdOBlbww/jIizagRo3UKQpKolO2mGIdywqEJRNwp4XiA1S8rTrqA0Sr0PSjWtAAAA==",
    "width": 2048,
    "height": 2048,
    "aspectRatio": 1
  },
  "ai_brain_network": {
    "src": "/imagery/processed/ai_brain_network-1200.webp",
    "src2x": "/imagery/processed/ai_brain_network-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZQCdAC0HmLlAAP7uF1RcOIrioJQHScTuG/qpKgAAAA==",
    "width": 1536,
    "height": 1024,
    "aspectRatio": 1.5
  },
  "home_hero_main": {
    "src": "/imagery/processed/ai_construction_bridge_banner-1200.webp",
    "src2x": "/imagery/processed/ai_construction_bridge_banner-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAwCdASoUAAsAPzmGulOvKSWisAgB4CcJYgC7ACHMy9W+r96d3wAA8pj5UDsJGTM83Dhj9AxuL4ucY6VEyisp8eF/liSMOEAAAA==",
    "width": 2816,
    "height": 1536,
    "aspectRatio": 1.8333333333333333
  },
  "home_hero_overlay": {
    "src": "/imagery/processed/ai_technology-1200.webp",
    "src2x": "/imagery/processed/ai_technology-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACwAwCdASoUAAwAPzmGvFQvKSYjMAgB4CcJQBUeg9XatQWRi9BtQAD+e9V4ROcIeW4jaHw1MP4nEeJcDUN8CtBC2TmF4AAA",
    "width": 834,
    "height": 500,
    "aspectRatio": 1.668
  },
  "animated_globe": {
    "src": "/imagery/processed/animated_globe-1200.webp",
    "src2x": "/imagery/processed/animated_globe-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAgCdASoUAA0APzmKulOvKaWisAgB4CcJZwAAQP64AAD+6O/fJ+rDzxTjiJY+rZlVFFFmiWdCAAAA",
    "width": 1536,
    "height": 1024,
    "aspectRatio": 1.5
  },
  "home_solution_security": {
    "src": "/imagery/processed/compliance_shield_premium-1200.webp",
    "src2x": "/imagery/processed/compliance_shield_premium-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQBACdASoUABQAPzGCtVOuqKUit/VYAdAmCWIAygAOGYFEydnIOcPw0AD+40pzVgFD7O9rIqUE9H3XkyWynqL/Eom/2hNiF1CcJH5U/4AAAA==",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1
  },
  "news_motif": {
    "src": "/imagery/processed/creation_AI-1200.webp",
    "src2x": "/imagery/processed/creation_AI-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwBACdASoUABQAPzmOvlevKaYjqAqp4CcJYgC/Z6AA0e60gO76r0ecEVAAJ9SjkAAA/qmwe/rWSvfWHH+Rup+ZTUl7Jpw8DNZkUCPmObdo4pj9KjblSOeluUycMMVsKnQZi9PqJ3U0mYX2Xfg6VE4zVyeEAAAA",
    "width": 1536,
    "height": 1536,
    "aspectRatio": 1
  },
  "home_solution_badge": {
    "src": "/imagery/processed/data_sovereignty_badge-1200.webp",
    "src2x": "/imagery/processed/data_sovereignty_badge-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQBACdASoUABQAPzmIt1OvKSUisBgMAeAnCWUAzBwY6ItfTztDBczkAAD+6vuG2rMnR1M2VzzWUF5pEvzEPY79Cx8hYAAA",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1
  },
  "earth": {
    "src": "/imagery/processed/earth-1200.webp",
    "src2x": "/imagery/processed/earth-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoUAAoAPzmGuVOvKSWisAgB4CcJYgCdACF5GzRCHGapgRAA+punTEGS9ZvhnHhRQ+mBZJr83n9vy1yN0hK+qL25wz3L0AAA",
    "width": 2048,
    "height": 1024,
    "aspectRatio": 2
  },
  "earth_daymap": {
    "src": "/imagery/processed/earth_daymap-1200.webp",
    "src2x": "/imagery/processed/earth_daymap-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAwCdASoUAAoAPzmGuVOvKSWisAgB4CcJYgCdACF5GzRCHGapgRAA+punTEGS9ZvhnHhRQ+mBZJr83n9vy1yN0hK+qL25wz3L0AAA",
    "width": 2048,
    "height": 1024,
    "aspectRatio": 2
  },
  "globe_base": {
    "src": "/imagery/processed/earth_globe_realistic-1200.webp",
    "src2x": "/imagery/processed/earth_globe_realistic-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADQAwCdASoUABQAPzmGvVOvKSaiqA1R4CcJQBhQARVdEsIfw3fhGAAA/ujpbMr/ZvmU1N7iTtSJwhy9SK19FCLCe8/jdH89DNeZ6fDxzeXEbvV4xkHc4XauXRlhJ54AAAA=",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1
  },
  "friendship": {
    "src": "/imagery/processed/friendship-1200.webp",
    "src2x": "/imagery/processed/friendship-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwBACdASoUABQAPzmKvFSvKaYjKA1R4CcJYwCw7AkooKlncdJ/K47FgvyiAAD+nvT+FMTyrPGLi8fKwkqX8NsfCpPt7W+yiSYsiaOYwJr6h3AHUQ+PjLHYHgF9tmAA",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1
  },
  "globe_3d_with_ravens": {
    "src": "/imagery/processed/globe_3d_with_ravens-1200.webp",
    "src2x": "/imagery/processed/globe_3d_with_ravens-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQBACdASoUABQAPzmGt1OvKSUisAgB4CcJZQDC+CHf46Q7OCLxJCG7lgMAAP7o2gUkfoPiqJY0Ex5IeZyArWqS1pHB40oAAAA=",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1
  },
  "huma_ai_space": {
    "src": "/imagery/processed/huma_AI-space-1200.webp",
    "src2x": "/imagery/processed/huma_AI-space-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQBACdASoUABIAPzmCu1OvKKaisBgMAeAnCUAX/YIXmnTTcQsSLwoctfWwAP7o0A/FILRGCNxEuYpnX+16uyLwytdAw9oS6lNUSQWfbXiNN0pK57LwtKPwYboskIAA",
    "width": 1536,
    "height": 1394,
    "aspectRatio": 1.1018651362984218
  },
  "human_ai_intothecosmos": {
    "src": "/imagery/processed/human_ai_intothecosmos-1200.webp",
    "src2x": "/imagery/processed/human_ai_intothecosmos-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABQBACdASoUABMAPzmAulOvJ6WisBgMAeAnCUAYbOZejYOaVRCq7mLQAVAAAP7kHE+gTe0ll9xdyOkPs/5LFkMxUD09kBAlM1pHnysMVd3Vu3TN9ZPoWbwov0XfwH+8rTiNmRw+SKh68HqSBBsJEGnGlkAAAA==",
    "width": 1440,
    "height": 1386,
    "aspectRatio": 1.0389610389610389
  },
  "footer_accent": {
    "src": "/imagery/processed/inspiring-1200.webp",
    "src2x": "/imagery/processed/inspiring-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoUAAsAPzmEulOvKKWisAgB4CcJZQAAT5shqJgAAO8TuRpU1xsT1q+g1w89N5Lxt8xOu/xv40CAAA==",
    "width": 1792,
    "height": 1024,
    "aspectRatio": 1.75
  },
  "integai_bio": {
    "src": "/imagery/processed/integai_bio-1200.webp",
    "src2x": "/imagery/processed/integai_bio-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAwCdASoUABMAPzmKulWvKSWjKA1R4CcJZwAALnZZORxKaEwLSpboAP7ozCiK36/P/DSvr6rybZ2tFwgIAA==",
    "width": 637,
    "height": 607,
    "aspectRatio": 1.0494233937397035
  },
  "footer_logo_integai": {
    "src": "/imagery/processed/integai_logo-1200.webp",
    "src2x": "/imagery/processed/integai_logo-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAwCdASoUABMAPzmKulWvKSWjKA1R4CcJZwAALnZZORxKaEwLSpboAP7ozCiK36/P/DSvr6rybZ2tFwgIAA==",
    "width": 637,
    "height": 607,
    "aspectRatio": 1.0494233937397035
  },
  "ireland_landscape": {
    "src": "/imagery/processed/ireland_landscape-1200.webp",
    "src2x": "/imagery/processed/ireland_landscape-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoUAA0APzmIu1QvKSYjMAgB4CcJbACdAB4IlTkbFt3tAADZM+l33jMmHN2g+0iNqlN1J+bxb9atFpK7UroFSpGSyDuxQTEEDmKyQmIEciYgNIAA",
    "width": 1900,
    "height": 1267,
    "aspectRatio": 1.499605367008682
  },
  "fusion_michael": {
    "src": "/imagery/processed/michael_howardbio-1200.webp",
    "src2x": "/imagery/processed/michael_howardbio-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBQCdASoUACAAPzmGuFOvKSUisAgB4CcJYgCdM2QCjjfkCQlBgFmtQ4ytYK8cdAKX4CcAAP65SOOi0o0F308Zs/Wv3AfW1tRLeqMb8N7tGxM6nOsgXTKKiYi+/XxmWlJ+PONQLNhFzjM3jY1Qt/2zq2iZiMAA",
    "width": 1266,
    "height": 2048,
    "aspectRatio": 0.6181640625
  },
  "globe_raven_huginn": {
    "src": "/imagery/processed/raven_huginn-1200.webp",
    "src2x": "/imagery/processed/raven_huginn-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwBACdASoUABQAPzGCtVOuqKUit/VYAdAmCWMAyrQQ70gSc5R1aqX51GfHIAD+5wrs8O81mVjbRKIWGZ/5KGiPaxJeyjd9A90CwGFUf/0nQC7T3AA=",
    "width": 2048,
    "height": 2048,
    "aspectRatio": 1
  },
  "globe_raven_muninn": {
    "src": "/imagery/processed/raven_muninn-1200.webp",
    "src2x": "/imagery/processed/raven_muninn-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAABwBACdASoUABQAPzGCtVOuqKUit/VYAdAmCWMAyrQQ70gSc5R1aqX51GfHIAD+5wrs8O81mVjbRKIWGZ/5KGiPaxJeyjd9A90CwGFUf/0nQC7T3AA=",
    "width": 2048,
    "height": 2048,
    "aspectRatio": 1
  },
  "poem_backdrop": {
    "src": "/imagery/processed/reach_for_the_stars-1200.webp",
    "src2x": "/imagery/processed/reach_for_the_stars-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwBACdASoUABQAPzmSvVgvKiYjqAqp4CcJZQCsABbJOCXcjsA8TXmOcoAA/umdvE73uc28liEUr5yFr8kvqpVd2COvXA9rxPdZT7QaP1IgXQX6IOwpQAZCSn3PQxAAAAA=",
    "width": 2048,
    "height": 2048,
    "aspectRatio": 1
  },
  "rotating_globe_animation": {
    "src": "/imagery/processed/rotating_globe_animation-1200.webp",
    "src2x": "/imagery/processed/rotating_globe_animation-2400.webp",
    "placeholder": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACQAwCdASoUABQAPzmKu1OvKiYisAgB4CcJZwDGBCHhvU2kCmAAAP7o3RWkNmd6bduiF0ENDa6BBmwAAAA=",
    "width": 1024,
    "height": 1024,
    "aspectRatio": 1
  }
} as const;

export type ImageId = keyof typeof IMAGES;

// Validation helpers
export function hasImage(imageId: string): imageId is ImageId {
  return imageId in IMAGES;
}

export function getImageInfo(imageId: ImageId) {
  return IMAGES[imageId];
}
